name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        numpy-version: ["<2", ">=2"]
        # NumPy 1.x only supports up to Python 3.12, so exclude Python 3.13 when testing with NumPy 1.x.
        # See https://numpy.org/doc/stable/release/1.26.0-notes.html#python-3-13-support
        exclude:
          - python-version: "3.13"
            numpy-version: "<2"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "numpy${{ matrix.numpy-version }}"
          pip install .[output]

      # Optional: show versions for debugging
      - name: Show environment
        run: |
          python --version
          python -c "import numpy; print('NumPy:', numpy.__version__)"
          python -c "import scipy; print('SciPy:', scipy.__version__)"
          python -c "import odrpack; print('ODRPack:', odrpack.__version__)"

      - name: Run unittests
        run: |
          python -m unittest discover -s unittests -t . -p "Test_*.py" -v
